.catalog:
  name: "Odoo"
  version: v0.1-dstadel
  description: "ERP management powered by Odoo"
  uuid: odoo-0
  questions:

odoo:
  scale: 1
  start_on_create: true
  health_check:
    healthy_threshold: 2
    response_timeout: 2000
    port: 42
    unhealthy_threshold: 3
    interval: 2000
    strategy: recreate
frepple:
  scale: 1
  start_on_create: true
  health_check:
    healthy_threshold: 2
    response_timeout: 2000
    port: 42
    unhealthy_threshold: 3
    interval: 2000
    strategy: recreate
postgres-data:
  scale: 1
  start_on_create: true
odoo-lb:
  scale: 1
  start_on_create: true
  lb_config:
    certs: []
    port_rules:
    - protocol: http
      service: odoo-db
      source_port: 5432
      target_port: 5432
  health_check:
    healthy_threshold: 2
    response_timeout: 2000
    port: 42
    unhealthy_threshold: 3
    interval: 2000
    strategy: recreate
odoo-db:
  scale: 1
  start_on_create: true
  health_check:
    healthy_threshold: 2
    response_timeout: 2000
    port: 5432
    unhealthy_threshold: 3
    interval: 2000
    strategy: recreate
frepple-lb:
  scale: 1
  start_on_create: true
  lb_config:
    certs: []
    port_rules:
    - protocol: http
      service: frepple-db
      source_port: 5433
      target_port: 5433
  health_check:
    healthy_threshold: 2
    response_timeout: 2000
    port: 42
    unhealthy_threshold: 3
    interval: 2000
    strategy: recreate
frepple-db:
  scale: 1
  start_on_create: true
  health_check:
    healthy_threshold: 2
    response_timeout: 2000
    port: 5433
    unhealthy_threshold: 3
    interval: 2000
    strategy: recreate
